INSERT INTO `country`(`id`, `name`, `position`) VALUES (1, 'Việt Nam', 0);

INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (1, 1, 'Hà Nội', 'Thành Phố', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (2, 1, 'Hà Giang', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (3, 1, 'Cao Bằng', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (4, 1, 'Bắc Kạn', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (5, 1, 'Tuyên Quang', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (6, 1, 'Lào Cai', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (7, 1, 'Điện Biên', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (8, 1, 'Lai Châu', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (9, 1, 'Sơn La', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (10, 1, 'Yên Bái', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (11, 1, 'Hòa Bình', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (12, 1, 'Thái Nguyên', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (13, 1, 'Lạng Sơn', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (14, 1, 'Quảng Ninh', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (15, 1, 'Bắc Giang', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (16, 1, 'Phú Thọ', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (17, 1, 'Vĩnh Phúc', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (18, 1, 'Bắc Ninh', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (19, 1, 'Hải Dương', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (20, 1, 'Hải Phòng', 'Thành Phố', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (21, 1, 'Hưng Yên', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (22, 1, 'Thái Bình', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (23, 1, 'Hà Nam', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (24, 1, 'Nam Định', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (25, 1, 'Ninh Bình', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (26, 1, 'Thanh Hóa', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (27, 1, 'Nghệ An', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (28, 1, 'Hà Tĩnh', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (29, 1, 'Quảng Bình', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (30, 1, 'Quảng Trị', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (31, 1, 'Thừa Thiên Huế', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (32, 1, 'Đà Nẵng', 'Thành Phố', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (33, 1, 'Quảng Nam', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (34, 1, 'Quảng Ngãi', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (35, 1, 'Bình Định', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (36, 1, 'Phú Yên', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (37, 1, 'Khánh Hòa', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (38, 1, 'Ninh Thuận', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (39, 1, 'Bình Thuận', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (40, 1, 'Kon Tum', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (41, 1, 'Gia Lai', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (42, 1, 'Đắk Lắk', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (43, 1, 'Đắk Nông', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (44, 1, 'Lâm Đồng', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (45, 1, 'Bình Phước', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (46, 1, 'Tây Ninh', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (47, 1, 'Bình Dương', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (48, 1, 'Đồng Nai', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (49, 1, 'Bà Rịa - Vũng Tàu', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (50, 1, 'Hồ Chí Minh', 'Thành Phố', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (51, 1, 'Long An', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (52, 1, 'Tiền Giang', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (53, 1, 'Bến Tre', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (54, 1, 'Trà Vinh', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (55, 1, 'Vĩnh Long', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (56, 1, 'Đồng Tháp', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (57, 1, 'An Giang', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (58, 1, 'Kiên Giang', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (59, 1, 'Cần Thơ', 'Thành Phố', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (60, 1, 'Hậu Giang', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (61, 1, 'Sóc Trăng', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (62, 1, 'Bạc Liêu', 'Tỉnh', 0);
INSERT INTO `city`(`id`, `country_id`, `name`, `type`, `position`) VALUES (63, 1, 'Cà Mau', 'Tỉnh', 0);
